spring:
  application:
    name=security
  flyway:
    table: schema_version
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: HikariInternalResPool
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
